annotationid: b1f07afe-5220-4106-b846-8fc08a319820
contentdisposition: 756150000
enabletracking: false
excludefromsearch: false
filename: .gitkeep
hiddenfromsitemap: false
id: 9860fc8b-c7ec-4082-885e-945c447e4e9c
isdocument: true
mimetype: application/octet-stream
name: .gitkeep
objectid: 9860fc8b-c7ec-4082-885e-945c447e4e9c
objecttypecode: adx_webfile
parentpageid: 677604eb-3b01-4c77-8382-afd411d35f1f
partialurl: .gitkeep
publishingstateid: 2633047a-946c-47be-918c-e7ab35e2fe57
